#!python

import os
import sys

gem5_arch = 'ARM'
gem5_variant = 'opt'

env = Environment()

print(f"ARGUMENTS = {ARGUMENTS}")

gem5_root_dir = ARGUMENTS.get('gem5_root', '#../../gem5')

gem5_root = Dir(gem5_root_dir).srcnode().abspath


print("root = ",  gem5_root)

#Make the gem5 root available in SConscripts
env['GEM5_ROOT'] = gem5_root
#This won't work with kconfig-based builds, where the build directory is
# not necessarily named "build".
env['GEM5BUILD'] = os.path.join(gem5_root, 'build')

shlibsuffix = env['SHLIBSUFFIX']

# add include dirs
env.Append(CPPPATH=[gem5_root + '/build/' + gem5_arch,
                    gem5_root + '/util/systemc/gem5_within_systemc',
                    gem5_root + '/util/tlm/examples/common',
                    gem5_root + '/util/tlm/src',
                    gem5_root + '/ext/systemc/src',
                    gem5_root + '/ext',
                    gem5_root + '/src',
                    '#gem5_tlm_src',
                    ])

env.Append(CXXFLAGS=['-std=c++17',
                     '-DSC_INCLUDE_DYNAMIC_PROCESSES',
                     '-DTRACING_ON',
                     ])

# An option not to link source files in the build directory.
# Not enabled by default.
AddOption('--no-duplicate-sources', action='store_false', default=True,
          dest='duplicate_sources',
          help='Do not create symlinks to sources in the build directory')

AddOption('--verbose', action='store_true',
          help='Print full tool command lines')

deps = [] # keep track of all dependencies required for building the binaries

deps += SConscript('gem5_tlm_src/SConscript', variant_dir='build/tlm', exports='env',
                   duplicate=GetOption('duplicate_sources'))

common = SConscript(gem5_root + '/util/tlm/examples/common/SConscript',
                   variant_dir='build/accelerator/common',
                   exports=['env'],
                   duplicate=GetOption('duplicate_sources'))

ignored_objects = {
    'cli_parser.o',
}

deps += [
    obj for obj in common
    if os.path.basename(str(obj)) not in ignored_objects
]

# the SystemC SConscript makes certain assumptions, we need to fulfill these
# assumptions before calling the SConscript.
#sys.path.append(gem5_root + '/src/python')
sys.path.append(os.path.join(gem5_root, 'src', 'python'))
sys.path.append(os.path.join(gem5_root, 'site_scons'))

AddOption('--no-colors', dest='use_colors', action='store_false',
          help="Don't add color to abbreviated scons output")

import gem5_scons

env.SConsignFile('build/systemc/sconsign')
SConscript(gem5_root + '/ext/systemc/SConscript',
           variant_dir='build/systemc',
           exports='env', duplicate=GetOption('duplicate_sources'))

# By adding libraries as dependencies instead of using LIBS, we avoid that
# the user needs to set the LD_LIBRARY_PATH
deps.append(File('build/systemc/libsystemc' + shlibsuffix))
deps.append(File(os.path.join(gem5_root, 'build', gem5_arch,
             'libgem5_' + gem5_variant + shlibsuffix)))

accelerator = SConscript('src/SConscript',
                      variant_dir='build/accelerator',
                      exports=['env', 'deps'],
                      duplicate=GetOption('duplicate_sources'))

Default(accelerator)
