#pragma once

#include <stdint.h>

// Register offsets generated by Vitis HLS for s_axi_control.
#define IMAGE_ACCEL_CTRL_OFFSET          0x00u
#define IMAGE_ACCEL_GIER_OFFSET          0x04u
#define IMAGE_ACCEL_IP_IER_OFFSET        0x08u
#define IMAGE_ACCEL_IP_ISR_OFFSET        0x0cu
#define IMAGE_ACCEL_INPUT_RGB_LOW_OFFSET 0x10u
#define IMAGE_ACCEL_INPUT_RGB_HIGH_OFFSET 0x14u
#define IMAGE_ACCEL_OUTPUT_LOW_OFFSET    0x1cu
#define IMAGE_ACCEL_OUTPUT_HIGH_OFFSET   0x20u
#define IMAGE_ACCEL_NUM_PIXELS_OFFSET    0x28u

#define IMAGE_ACCEL_CTRL_AP_START        0x00000001u
#define IMAGE_ACCEL_CTRL_AP_DONE         0x00000002u
#define IMAGE_ACCEL_CTRL_AP_IDLE         0x00000004u
#define IMAGE_ACCEL_CTRL_AP_READY        0x00000008u
#define IMAGE_ACCEL_CTRL_AUTO_RESTART    0x00000080u

#define IMAGE_ACCEL_WIDTH                1920u
#define IMAGE_ACCEL_HEIGHT               1080u
#define IMAGE_ACCEL_NUM_PIXELS           (IMAGE_ACCEL_WIDTH * IMAGE_ACCEL_HEIGHT)
#define IMAGE_ACCEL_RGB_BYTES            (IMAGE_ACCEL_NUM_PIXELS * 3u)
#define IMAGE_ACCEL_GRAY_BYTES           IMAGE_ACCEL_NUM_PIXELS

#ifdef __cplusplus
extern "C" {
#endif

void image_accel_write_reg(uintptr_t base_addr, uint32_t offset, uint32_t value);
uint32_t image_accel_read_reg(uintptr_t base_addr, uint32_t offset);

void image_accel_set_input_rgb(uintptr_t base_addr, uint64_t input_rgb_addr);
void image_accel_set_output_gray(uintptr_t base_addr, uint64_t output_gray_addr);
void image_accel_set_num_pixels(uintptr_t base_addr, uint32_t num_pixels);

void image_accel_start(uintptr_t base_addr);
uint32_t image_accel_is_done(uintptr_t base_addr);
uint32_t image_accel_is_idle(uintptr_t base_addr);

// Returns 0 on completion, -1 on timeout.
int image_accel_wait_done(uintptr_t base_addr, uint32_t timeout_iterations);

// Configures and runs one RGB-to-grayscale transaction.
// The input buffer is RAW RGB888. The output buffer receives one grayscale byte
// per pixel.
int image_accel_run(uintptr_t base_addr,
                    uint64_t input_rgb_addr,
                    uint64_t output_gray_addr,
                    uint32_t num_pixels,
                    uint32_t timeout_iterations);

#ifdef __cplusplus
}
#endif

