// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module image_accel_p_anonymous_namespace_read_input (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        input_rgb,
        rgb_stream_din,
        rgb_stream_num_data_valid,
        rgb_stream_fifo_cap,
        rgb_stream_full_n,
        rgb_stream_write,
        num_pixels,
        num_pixels_c1_din,
        num_pixels_c1_num_data_valid,
        num_pixels_c1_fifo_cap,
        num_pixels_c1_full_n,
        num_pixels_c1_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [7:0] m_axi_gmem0_WDATA;
output  [0:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [7:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [12:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] input_rgb;
output  [23:0] rgb_stream_din;
input  [6:0] rgb_stream_num_data_valid;
input  [6:0] rgb_stream_fifo_cap;
input   rgb_stream_full_n;
output   rgb_stream_write;
input  [31:0] num_pixels;
output  [31:0] num_pixels_c1_din;
input  [2:0] num_pixels_c1_num_data_valid;
input  [2:0] num_pixels_c1_fifo_cap;
input   num_pixels_c1_full_n;
output   num_pixels_c1_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;
reg rgb_stream_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    num_pixels_c1_blk_n;
reg    ap_block_state1;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_done;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_idle;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_ready;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWVALID;
wire   [63:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWADDR;
wire   [0:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWID;
wire   [31:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWLEN;
wire   [2:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWSIZE;
wire   [1:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWBURST;
wire   [1:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWLOCK;
wire   [3:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWCACHE;
wire   [2:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWPROT;
wire   [3:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWQOS;
wire   [3:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWREGION;
wire   [0:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWUSER;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WVALID;
wire   [7:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WDATA;
wire   [0:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WSTRB;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WLAST;
wire   [0:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WID;
wire   [0:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WUSER;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARVALID;
wire   [63:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARADDR;
wire   [0:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARID;
wire   [31:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARLEN;
wire   [2:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARSIZE;
wire   [1:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARBURST;
wire   [1:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARLOCK;
wire   [3:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARCACHE;
wire   [2:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARPROT;
wire   [3:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARQOS;
wire   [3:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARREGION;
wire   [0:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARUSER;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_RREADY;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_BREADY;
wire   [23:0] grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_rgb_stream_din;
wire    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_rgb_stream_write;
reg    grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    num_pixels_c1_write_local;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start_reg = 1'b0;
end

image_accel_p_anonymous_namespace_read_input_Pipeline_read_loop grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start),
    .ap_done(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_done),
    .ap_idle(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_ready),
    .m_axi_gmem0_AWVALID(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .num_pixels(num_pixels),
    .input_rgb(input_rgb),
    .rgb_stream_din(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_rgb_stream_din),
    .rgb_stream_num_data_valid(7'd0),
    .rgb_stream_fifo_cap(7'd0),
    .rgb_stream_full_n(rgb_stream_full_n),
    .rgb_stream_write(grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_rgb_stream_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_done == 1'b1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_ARVALID = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARVALID;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem0_RREADY = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_RREADY;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_c1_blk_n = num_pixels_c1_full_n;
    end else begin
        num_pixels_c1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        num_pixels_c1_write_local = 1'b1;
    end else begin
        num_pixels_c1_write_local = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        rgb_stream_write = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_rgb_stream_write;
    end else begin
        rgb_stream_write = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1) | (num_pixels_c1_full_n == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_ap_start_reg;

assign m_axi_gmem0_ARADDR = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 8'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 1'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign num_pixels_c1_din = num_pixels;

assign num_pixels_c1_write = num_pixels_c1_write_local;

assign rgb_stream_din = grp_p_anonymous_namespace_read_input_Pipeline_read_loop_fu_70_rgb_stream_din;

assign start_out = real_start;

endmodule //image_accel_p_anonymous_namespace_read_input
