// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module image_accel_p_anonymous_namespace_write_output (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        output_gray_dout,
        output_gray_num_data_valid,
        output_gray_fifo_cap,
        output_gray_empty_n,
        output_gray_read,
        gray_stream_dout,
        gray_stream_num_data_valid,
        gray_stream_fifo_cap,
        gray_stream_empty_n,
        gray_stream_read,
        num_pixels_dout,
        num_pixels_num_data_valid,
        num_pixels_fifo_cap,
        num_pixels_empty_n,
        num_pixels_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [7:0] m_axi_gmem1_WDATA;
output  [0:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [7:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [10:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] output_gray_dout;
input  [2:0] output_gray_num_data_valid;
input  [2:0] output_gray_fifo_cap;
input   output_gray_empty_n;
output   output_gray_read;
input  [7:0] gray_stream_dout;
input  [6:0] gray_stream_num_data_valid;
input  [6:0] gray_stream_fifo_cap;
input   gray_stream_empty_n;
output   gray_stream_read;
input  [31:0] num_pixels_dout;
input  [2:0] num_pixels_num_data_valid;
input  [2:0] num_pixels_fifo_cap;
input   num_pixels_empty_n;
output   num_pixels_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem1_AWVALID;
reg m_axi_gmem1_WVALID;
reg m_axi_gmem1_BREADY;
reg gray_stream_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    output_gray_blk_n;
reg    num_pixels_blk_n;
reg   [31:0] num_pixels_1_reg_68;
reg    ap_block_state1;
reg   [63:0] output_gray_1_reg_73;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_done;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_idle;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_ready;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_gray_stream_read;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWVALID;
wire   [63:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWADDR;
wire   [0:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWID;
wire   [31:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWLEN;
wire   [2:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWSIZE;
wire   [1:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWBURST;
wire   [1:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWLOCK;
wire   [3:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWCACHE;
wire   [2:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWPROT;
wire   [3:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWQOS;
wire   [3:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWREGION;
wire   [0:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWUSER;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WVALID;
wire   [7:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WDATA;
wire   [0:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WSTRB;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WLAST;
wire   [0:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WID;
wire   [0:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WUSER;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARVALID;
wire   [63:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARADDR;
wire   [0:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARID;
wire   [31:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARLEN;
wire   [2:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARSIZE;
wire   [1:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARBURST;
wire   [1:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARLOCK;
wire   [3:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARCACHE;
wire   [2:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARPROT;
wire   [3:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARQOS;
wire   [3:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARREGION;
wire   [0:0] grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARUSER;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_RREADY;
wire    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_BREADY;
reg    grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    num_pixels_read_local;
reg    output_gray_read_local;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start_reg = 1'b0;
end

image_accel_p_anonymous_namespace_write_output_Pipeline_write_loop grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start),
    .ap_done(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_done),
    .ap_idle(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_ready),
    .gray_stream_dout(gray_stream_dout),
    .gray_stream_num_data_valid(7'd0),
    .gray_stream_fifo_cap(7'd0),
    .gray_stream_empty_n(gray_stream_empty_n),
    .gray_stream_read(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_gray_stream_read),
    .m_axi_gmem1_AWVALID(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(m_axi_gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(m_axi_gmem1_WREADY),
    .m_axi_gmem1_WDATA(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(8'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(11'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(m_axi_gmem1_BVALID),
    .m_axi_gmem1_BREADY(grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(m_axi_gmem1_BRESP),
    .m_axi_gmem1_BID(m_axi_gmem1_BID),
    .m_axi_gmem1_BUSER(m_axi_gmem1_BUSER),
    .num_pixels_1(num_pixels_1_reg_68),
    .output_gray_1(output_gray_1_reg_73)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        num_pixels_1_reg_68 <= num_pixels_dout;
        output_gray_1_reg_73 <= output_gray_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gray_stream_read = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_gray_stream_read;
    end else begin
        gray_stream_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem1_AWVALID = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWVALID;
    end else begin
        m_axi_gmem1_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem1_BREADY = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_BREADY;
    end else begin
        m_axi_gmem1_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        m_axi_gmem1_WVALID = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WVALID;
    end else begin
        m_axi_gmem1_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        num_pixels_blk_n = num_pixels_empty_n;
    end else begin
        num_pixels_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        num_pixels_read_local = 1'b1;
    end else begin
        num_pixels_read_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        output_gray_blk_n = output_gray_empty_n;
    end else begin
        output_gray_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        output_gray_read_local = 1'b1;
    end else begin
        output_gray_read_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((num_pixels_empty_n == 1'b0) | (ap_start == 1'b0) | (output_gray_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_ap_start_reg;

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWADDR;

assign m_axi_gmem1_AWBURST = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWBURST;

assign m_axi_gmem1_AWCACHE = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWCACHE;

assign m_axi_gmem1_AWID = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWID;

assign m_axi_gmem1_AWLEN = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWLEN;

assign m_axi_gmem1_AWLOCK = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWLOCK;

assign m_axi_gmem1_AWPROT = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWPROT;

assign m_axi_gmem1_AWQOS = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWQOS;

assign m_axi_gmem1_AWREGION = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWREGION;

assign m_axi_gmem1_AWSIZE = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWSIZE;

assign m_axi_gmem1_AWUSER = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_AWUSER;

assign m_axi_gmem1_RREADY = 1'b0;

assign m_axi_gmem1_WDATA = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WDATA;

assign m_axi_gmem1_WID = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WID;

assign m_axi_gmem1_WLAST = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WLAST;

assign m_axi_gmem1_WSTRB = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WSTRB;

assign m_axi_gmem1_WUSER = grp_p_anonymous_namespace_write_output_Pipeline_write_loop_fu_58_m_axi_gmem1_WUSER;

assign num_pixels_read = num_pixels_read_local;

assign output_gray_read = output_gray_read_local;

endmodule //image_accel_p_anonymous_namespace_write_output
