#!python

Import('env')

env = env.Clone()

gem5_root = env['GEM5_ROOT']

systemc_util_dir = gem5_root + '/util/systemc/gem5_within_systemc'

tlm_util_dir = gem5_root + '/util/tlm/src'

systemc_src = []
systemc_src += Install('.', systemc_util_dir + '/sc_gem5_control.cc'),
systemc_src += Install('.', systemc_util_dir + '/sc_logger.cc'),
systemc_src += Install('.', systemc_util_dir + '/sc_module.cc'),
systemc_src += Install('.', systemc_util_dir + '/stats.cc'),

tlm_src = []
tlm_src += Install('.', tlm_util_dir + '/sc_ext.cc')
tlm_src += Install('.', tlm_util_dir + '/sc_mm.cc')
tlm_src += Install('.', tlm_util_dir + '/sc_slave_port.cc')
tlm_src += Install('.', tlm_util_dir + '/sim_control.cc')
tlm_src += Install('.', tlm_util_dir + '/slave_transactor.cc')

tlm = env.Library('gem5_tlm', tlm_src + systemc_src)

Return('tlm')